# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=40)),
                ('deck_format', models.CharField(choices=[(b'STD', b'Standard'), (b'MDN', b'Modern'), (b'LGC', b'Legacy'), (b'VTG', b'Vintage'), (b'EDH', b'Commander/EDH'), (b'PAU', b'Pauper')], max_length=10)),
                ('deck_price_paper', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('deck_price_online', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('deck_privacy', models.BooleanField()),
                ('deck_need_feedback', models.BooleanField()),
                ('deck_rating', models.IntegerField()),
                ('deck_last_edited', models.DateTimeField()),
                ('deck_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None)),
            ],
        ),
    ]
