# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='decklist_mainboard',
            field=models.CharField(max_length=200),
        ),
    ]
