# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_auto_20160919_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='decklist_sideboard',
            field=models.TextField(default=b'Please place each card on a new line. \nFormating Sample: \n4x Storm Crow \n4x Doom Blade'),
        ),
    ]
