# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_auto_20161114_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='decklist_mainboard',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='deck',
            name='decklist_sideboard',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
