# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brew', '0003_deck_decklist_sideboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
