# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 15:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_auto_20161114_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('card_price_paper', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('card_price_online', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_description',
            field=redactor.fields.RedactorField(verbose_name='Deck Description'),
        ),
    ]
