# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_deck_deck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_description',
            field=models.CharField(default=b'Enter description here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='deck',
            name='decklist_mainboard',
            field=models.CharField(default=b'Please place each card on a new line. \nFormating Sample: \n4x Storm Crow \n4x Doom Blade', max_length=100),
        ),
        migrations.AlterField(
            model_name='deck',
            name='decklist_sideboard',
            field=models.CharField(default=b'Please place each card on a new line. \nFormating Sample: \n4x Storm Crow \n4x Doom Blade', max_length=15),
        ),
    ]
