# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_auto_20161230_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
