# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-02 16:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0005_auto_20161230_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_price_online',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_price_paper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
