# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:51
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0005_auto_20160926_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
