# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 15:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0007_cardstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstore',
            name='digital_store',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='cardstore',
            name='paper_store',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
    ]
