# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-04 17:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0009_auto_20170103_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCardStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_store', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='PaperCardStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_store', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='CardStore',
        ),
    ]
